### ISSUE TITLE
Разве деньги списываются не при смене тарифа?

### ISSUE THREAD

**Issue by etomarat** [kovetskiy/yota-cli#3]
Привет! Разве когда меняешь тариф деньги не списываются сразу же в момент смены? Расскажи пожалуйста как это работает на самом деле. Они считают сколько на какой скорости ты пользовался и в конце месяца формируется счёт или как?

**Comment by NMelis** [comment]
Привет, неа, не списывают деньги, когда меняете тариф

**Comment by kovetskiy** [comment]
Привет, базовое списание только при выборе тарифа, а потом уже поминутно
(этот момент я точно не знаю, может по пять минут) списываются деньги.

**Comment by etomarat** [comment]
Т.е. вначале месяца нужно выбирать минимальный тариф а потом уже переключать?

**Comment by kovetskiy** [comment]
Можно брать любой тариф, просто потом менять его на нужный.
